# Generated by Django 5.0 on 2025-07-23 12:10

import ckeditor.fields
import django.utils.timezone
import noticias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da notícia', max_length=200, verbose_name='Título')),
                ('conteudo', ckeditor.fields.RichTextField(help_text='Conteúdo completo da notícia com formatação rica', verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem destacada da notícia', null=True, upload_to=noticias.models.noticia_image_upload_path, verbose_name='Imagem')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('publicada', models.BooleanField(default=True, help_text='Notícia visível ao público', verbose_name='Publicada')),
                ('destaque', models.BooleanField(default=False, help_text='Exibir como notícia em destaque', verbose_name='Destaque')),
                ('autor', models.CharField(blank=True, help_text='Autor da notícia (opcional)', max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
