# Generated by Django 5.0 on 2025-07-23 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('escola_samba', 'Escola de Samba'), ('bloco_rua', 'Bloco de Rua')], max_length=20, unique=True, verbose_name='Categoria')),
                ('total_votos', models.PositiveIntegerField(default=0, verbose_name='Total de Votos')),
                ('ultimo_update', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Resultado da Votação',
                'verbose_name_plural': 'Resultados da Votação',
            },
        ),
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Chave da Sessão')),
                ('device_id', models.CharField(max_length=64, verbose_name='ID do Dispositivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('votes_count', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Votos')),
            ],
            options={
                'verbose_name': 'Sessão de Votação',
                'verbose_name_plural': 'Sessões de Votação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('escola_samba', 'Escola de Samba'), ('bloco_rua', 'Bloco de Rua')], max_length=20, verbose_name='Categoria')),
                ('device_id', models.CharField(help_text='Hash SHA-256 do IP + User-Agent', max_length=64, verbose_name='ID do Dispositivo')),
                ('ip_address', models.GenericIPAddressField(help_text='IP do votante (para auditoria)', verbose_name='Endereço IP')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Voto')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='grupos.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['categoria', 'grupo'], name='votacao_vot_categor_3cb163_idx'), models.Index(fields=['device_id'], name='votacao_vot_device__9da162_idx'), models.Index(fields=['timestamp'], name='votacao_vot_timesta_c24579_idx')],
                'unique_together': {('device_id', 'categoria')},
            },
        ),
    ]
