# Generated by Django 5.0 on 2025-07-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=50, unique=True)),
                ('third_party_reference', models.CharField(max_length=50, unique=True)),
                ('customer_msisdn', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_code', models.CharField(blank=True, max_length=20, null=True)),
                ('response_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(choices=[('escola_samba', 'Escola de Samba'), ('bloco_rua', 'Bloco de Rua')], max_length=20)),
                ('device_id', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_reference'], name='votacao_pay_transac_c6d2c3_idx'), models.Index(fields=['conversation_id'], name='votacao_pay_convers_fbdb5e_idx'), models.Index(fields=['device_id', 'categoria'], name='votacao_pay_device__7602d6_idx'), models.Index(fields=['status'], name='votacao_pay_status_ca8ffe_idx')],
            },
        ),
    ]
