# Generated by Django 5.0 on 2025-07-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_add_categoria_model'),
        ('votacao', '0002_payment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voto',
            new_name='votacao_vot_categor_ed250c_idx',
            old_name='votacao_vot_categor_3cb163_idx',
        ),
        migrations.AlterField(
            model_name='resultadovotacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.categoria', unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.categoria', verbose_name='Categoria'),
        ),
    ]
