# Generated by Django 5.0 on 2025-07-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_add_categoria_model'),
        ('votacao', '0003_rename_votacao_vot_categor_3cb163_idx_votacao_vot_categor_ed250c_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='votacao_pay_device__cd622f_idx',
            old_name='votacao_pay_device__7602d6_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.categoria', verbose_name='Categoria'),
        ),
    ]
