# Generated by Django 5.0 on 2025-07-23 12:10

import django.core.validators
import django.utils.timezone
import grupos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(help_text='Nome único do grupo carnavalesco', max_length=100, unique=True, verbose_name='Nome do Grupo')),
                ('representante', models.CharField(max_length=100, verbose_name='Representante')),
                ('contato', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Contato deve ser um telefone válido (ex: (11) 99999-9999) ou email válido', regex='^(\\+?55\\s?)?\\(?([1-9]{2})\\)?\\s?9?\\d{4}-?\\d{4}$|^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='Contato')),
                ('descricao', models.TextField(help_text='Descrição do grupo e sua história', verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('escola_samba', 'Escola de Samba'), ('bloco_rua', 'Bloco de Rua')], max_length=20, verbose_name='Categoria')),
                ('data_inscricao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inscrição')),
                ('foto', models.ImageField(blank=True, help_text='Foto representativa do grupo', null=True, upload_to=grupos.models.grupo_photo_upload_path, verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, help_text='Grupo ativo para participação', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nome_grupo'],
            },
        ),
    ]
