# Generated by Django 5.0 on 2025-07-25 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria (ex: Escola de Samba, Bloco de Rua)', max_length=50, unique=True, verbose_name='Nome da Categoria')),
                ('codigo', models.SlugField(help_text='Código único para a categoria (ex: escola_samba, bloco_rua)', unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da categoria', verbose_name='Descrição')),
                ('icone', models.CharField(default='bi-people', help_text='Ícone Bootstrap Icons (ex: bi-star, bi-people, bi-music-note)', max_length=50, verbose_name='Ícone Bootstrap')),
                ('cor_primaria', models.CharField(default='#FF6B35', help_text='Cor primária em hexadecimal (ex: #FF6B35)', max_length=7, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#F7931E', help_text='Cor secundária em hexadecimal (ex: #F7931E)', max_length=7, verbose_name='Cor Secundária')),
                ('ativa', models.BooleanField(default=True, help_text='Categoria disponível para novos grupos', verbose_name='Ativa')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (0 = primeiro)', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='grupo',
            name='categoria',
            field=models.ForeignKey(help_text='Categoria do grupo', on_delete=django.db.models.deletion.PROTECT, to='grupos.categoria', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Participante')),
                ('funcao', models.CharField(blank=True, help_text='Função no grupo (ex: Diretor, Mestre-sala, Porta-bandeira)', max_length=50, verbose_name='Função')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato (opcional)', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, help_text='Email de contato (opcional)', max_length=254, verbose_name='Email')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento (opcional)', null=True, verbose_name='Data de Nascimento')),
                ('ativo', models.BooleanField(default=True, help_text='Participante ativo no grupo', verbose_name='Ativo')),
                ('data_adicao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Adição')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='grupos.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['nome'],
                'unique_together': {('grupo', 'nome')},
            },
        ),
    ]
